# Generated by Django 2.2.11 on 2020-03-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transformer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('deviceid', models.CharField(default='pv01', max_length=200)),
                ('tempindoor', models.FloatField(blank=True, default=0, null=True)),
                ('tempoutdoor', models.FloatField(blank=True, default=0, null=True)),
                ('powera', models.FloatField(blank=True, default=0, null=True)),
                ('powerb', models.FloatField(blank=True, default=0, null=True)),
                ('powerc', models.FloatField(blank=True, default=0, null=True)),
                ('powertot', models.FloatField(blank=True, default=0, null=True)),
                ('reactivepowera', models.FloatField(blank=True, default=0, null=True)),
                ('reactivepowerb', models.FloatField(blank=True, default=0, null=True)),
                ('reactivepowerc', models.FloatField(blank=True, default=0, null=True)),
                ('reactivepowertot', models.FloatField(blank=True, default=0, null=True)),
                ('currenta', models.FloatField(blank=True, default=0, null=True)),
                ('currentb', models.FloatField(blank=True, default=0, null=True)),
                ('currentc', models.FloatField(blank=True, default=0, null=True)),
                ('currenttot', models.FloatField(blank=True, default=0, null=True)),
                ('voltagea', models.FloatField(blank=True, default=0, null=True)),
                ('voltageb', models.FloatField(blank=True, default=0, null=True)),
                ('voltagec', models.FloatField(blank=True, default=0, null=True)),
                ('voltagetot', models.FloatField(blank=True, default=0, null=True)),
                ('kwha', models.FloatField(blank=True, default=0, null=True)),
                ('kwhb', models.FloatField(blank=True, default=0, null=True)),
                ('kwhc', models.FloatField(blank=True, default=0, null=True)),
                ('kwhtot', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
