# Generated by Django 2.2.11 on 2020-03-18 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlmapi', '0002_transformer_pub_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformer',
            name='pub_time',
        ),
    ]
