# Generated by Django 2.2.11 on 2020-03-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlmapi', '0003_remove_transformer_pub_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformer',
            name='pub_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
