# Generated by Django 2.2.11 on 2020-03-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlmapi', '0004_transformer_pub_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformer',
            name='pub_time',
            field=models.TimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
