# Generated by Django 2.2.11 on 2020-03-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlmapi', '0005_auto_20200319_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformer',
            name='pub_time',
            field=models.TimeField(blank=True, null=True, verbose_name='time published'),
        ),
    ]
