# Generated by Django 2.2.11 on 2020-03-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlmapi', '0007_auto_20200319_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformer',
            name='deviceid',
            field=models.CharField(default='pv01', max_length=200),
        ),
        migrations.AlterField(
            model_name='transformer',
            name='pub_time',
            field=models.TimeField(blank=True, null=True, verbose_name='time published'),
        ),
    ]
