# Generated by Django 3.0.4 on 2020-03-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlmapi', '0008_auto_20200319_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='transformer2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('pub_time', models.TimeField(blank=True, null=True, verbose_name='time published')),
                ('deviceid', models.CharField(default='pv01', max_length=200)),
                ('grid', models.FloatField(blank=True, default=0, null=True)),
                ('load', models.FloatField(blank=True, default=0, null=True)),
                ('solar', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
